#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndroidTips.Resource", IsApplication=true)]

namespace AndroidTips
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_stat_button_click = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int idf = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int btnGo = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int btnImageScaleType = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int btnKeyboard = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int btnLocalNotification = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int btnSend = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int scaleImageView = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int selectImageScaleType = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int txtMessage = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int txtReceived = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int txtUrl = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int webView = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int ImageScaleTypeView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int KeyboardInputView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int LocalNotificationView = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int NotificationProcessingView = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
